// demos/vue/persp/src/components/ZHTMLRenderViewPersp.vue
<script lang="ts">
import { defineComponent } from 'vue';
import { ZHTMLRenderTarget } from 'zhtml';

export default defineComponent({
	name: 'ZHTMLRenderViewPersp',
	props: {
		renderTarget: {
			type: Object as () => ZHTMLRenderTarget,
			required: true,
		},
		glContainerName: {
			type: String,
			default: 'gl_container_name',
		},
	},
	setup() {
		return {};
	},
});
</script>

<template>
	<div class="absolute left-0 top-0 right-0 bottom-0">
		<div
			v-if="renderTarget"
			:data-render-target-uuid="renderTarget.uuid"
			data-render-target-type="scene"
			class="absolute left-0 top-0 w-full h-full"
		>
			<div
				:data-render-target-uuid="renderTarget.uuid"
				data-render-target-type="camera"
			>
				<slot name="content" />
			</div>
		</div>

		<div
			:name="glContainerName"
			class="absolute left-0 top-0 w-full h-full pointer-events-none"
		/>
	</div>
</template>

// demos/react/persp/src/components/ZHTMLRenderViewPersp.tsx
import { ReactNode } from 'react';
import type { ZHTMLRenderTarget } from 'zhtml';

interface ZHTMLRenderViewPerspProps {
	renderTarget: ZHTMLRenderTarget;
	glContainerName?: string;
	className?: string;
	children?: ReactNode;
}

export function ZHTMLRenderViewPersp({
	renderTarget,
	glContainerName = 'gl_container_name',
	className,
	children,
}: ZHTMLRenderViewPerspProps) {
	return (
		<div className={className || 'absolute left-0 top-0 right-0 bottom-0'}>
			<div
				data-render-target-uuid={renderTarget.uuid}
				data-render-target-type="scene"
				className="absolute left-0 top-0 w-full h-full"
			>
				<div
					data-render-target-uuid={renderTarget.uuid}
					data-render-target-type="camera"
				>
					{children}
				</div>
			</div>

			<div
				// @ts-expect-error name is valid for querySelector
				name={glContainerName}
				className="absolute left-0 top-0 w-full h-full pointer-events-none"
			/>
		</div>
	);
}
